# Generated by Django 4.2.13 on 2025-09-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='الصورة الشخصية'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='الصورة الشخصية'),
        ),
    ]
