# Generated by Django 4.2.13 on 2025-09-27 19:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0002_employee_profile_picture_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('manager', 'Manager')], default='employee', max_length=20),
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='وقت الحضور')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='وقت الانصراف')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر'), ('on_leave', 'إجازة')], default='present', max_length=20, verbose_name='الحالة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_management.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'الحضور والانصراف',
                'verbose_name_plural': 'الحضور والانصراف',
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
