# Generated by Django 4.2.13 on 2025-09-28 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0003_user_role_employeeattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='shift_end_time',
            field=models.TimeField(default=datetime.time(17, 0), verbose_name='وقت الانتهاء التبديل'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_start_time',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='وقت التبديل'),
        ),
    ]
