# Generated by Django 4.2.13 on 2025-09-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0005_alter_employeeattendance_date_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='paid',
            field=models.BooleanField(default=True, verbose_name='المدفوعة'),
        ),
    ]
