# Generated by Django 4.2.13 on 2025-09-28 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0006_employeeattendance_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الشكوى')),
                ('description', models.TextField(verbose_name='تفاصيل الشكوى')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('in_review', 'تحت المراجعة'), ('answered', 'تم الرد'), ('closed', 'مغلقة')], default='open', max_length=20, verbose_name='الحالة')),
                ('attachment_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط مرفق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_management.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'شكوى',
                'verbose_name_plural': 'الشكاوى',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='ahmed', max_length=200, verbose_name='الاسم'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ComplaintReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='الرد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرد')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='hr_management.complaint', verbose_name='الشكوى')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رد على الشكوى',
                'verbose_name_plural': 'ردود الشكاوى',
            },
        ),
        migrations.CreateModel(
            name='ComplaintAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(verbose_name='رابط الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='hr_management.complaint')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='hr_management.complaintreply')),
            ],
            options={
                'verbose_name': 'مرفق شكوى/رد',
                'verbose_name_plural': 'مرفقات الشكاوى/الردود',
            },
        ),
    ]
