# Generated by Django 4.2.13 on 2025-09-28 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0007_complaint_user_name_complaintreply_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
    ]
