# Generated by Django 4.2.13 on 2025-09-28 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0008_remove_employee_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='urgency',
            field=models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عال')], default='low', max_length=20, verbose_name='العاجمية'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='hr_management.employee', verbose_name='الموظف'),
        ),
    ]
