# Generated by Django 4.2.13 on 2025-09-29 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0010_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_management.employee', verbose_name='الموظف'),
        ),
    ]
