# Generated by Django 4.2.13 on 2025-09-29 15:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0011_alter_wallet_balance_alter_wallet_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReimbursementRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('status', models.CharField(choices=[('pending', 'تحت المراجعة'), ('approved', 'موافقة'), ('rejected', 'رفض')], default='pending', max_length=20)),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='رد الأدمن')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursements', to='hr_management.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ReimbursementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(verbose_name='رابط الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reimbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='hr_management.reimbursementrequest')),
            ],
        ),
    ]
