# Generated by Django 4.2.13 on 2025-09-29 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0012_reimbursementrequest_reimbursementattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='hr_management.employee', verbose_name='الموظف'),
        ),
    ]
