# Generated by Django 4.2.13 on 2025-10-01 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0013_alter_wallet_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='المعدل المتوسط للوقت الإضافي'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='urgency',
            field=models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عال')], default='low', max_length=20, verbose_name='الاهمية'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 1, 11, 43, 53, 744584, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
