# Generated by Django 4.2.13 on 2025-10-04 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0014_employee_overtime_rate_alter_complaint_urgency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 4, 11, 50, 10, 960152, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
