# Generated by Django 4.2.13 on 2025-10-04 13:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0015_alter_employeeattendance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Task Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Task Description')),
                ('status', models.CharField(choices=[('to_do', 'To Do'), ('doing', 'Doing'), ('done', 'Done')], default='to_do', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Task Date')),
                ('assigned_by_manager', models.BooleanField(default=False, verbose_name='Assigned by Manager')),
                ('estimated_minutes', models.IntegerField(default=30, verbose_name='Estimated Time (minutes)')),
                ('actual_minutes', models.IntegerField(blank=True, null=True, verbose_name='Actual Time (minutes)')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Task Notes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='hr_management.employee')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-priority', 'created_at'],
                'unique_together': {('employee', 'title', 'date')},
            },
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 4, 13, 26, 18, 724762, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_manager_note', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hr_management.task')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('total_tasks', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('in_progress_tasks', models.IntegerField(default=0)),
                ('not_completed_tasks', models.IntegerField(default=0)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('summary_notes', models.TextField(blank=True, null=True, verbose_name='Daily Summary')),
                ('challenges_faced', models.TextField(blank=True, null=True, verbose_name='Challenges/Issues')),
                ('achievements', models.TextField(blank=True, null=True, verbose_name='Key Achievements')),
                ('tomorrow_priorities', models.TextField(blank=True, null=True, verbose_name="Tomorrow's Priorities")),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by_manager', models.BooleanField(default=False)),
                ('manager_feedback', models.TextField(blank=True, null=True, verbose_name='Manager Feedback')),
                ('manager_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_reports', to='hr_management.employee')),
            ],
            options={
                'verbose_name': 'Task Report',
                'verbose_name_plural': 'Task Reports',
                'ordering': ['-date', 'employee__name'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
