# Generated by Django 4.2.13 on 2025-10-04 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0016_task_alter_employeeattendance_date_taskcomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 4, 13, 47, 53, 381626, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
