# Generated by Django 4.2.13 on 2025-10-04 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0018_alter_employeeattendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 4, 14, 4, 26, 157438, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
