# Generated by Django 4.2.13 on 2025-10-04 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0020_alter_task_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Deadline'),
        ),
        migrations.AddField(
            model_name='task',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Paused At'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='task',
            name='total_pause_time',
            field=models.IntegerField(default=0, verbose_name='Total Pause Time (minutes)'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 4, 14, 33, 39, 213388, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
