# Generated by Django 4.2.13 on 2025-10-05 07:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0021_task_end_date_task_paused_at_task_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 5, 7, 10, 3, 870966, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift_type', models.CharField(choices=[('regular', 'Regular Shift'), ('overtime', 'Overtime Shift'), ('emergency', 'Emergency Shift'), ('meeting', 'Meeting/Training')], default='regular', max_length=20, verbose_name='نوع الوردية')),
                ('check_in', models.DateTimeField(verbose_name='وقت بداية الوردية')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='وقت نهاية الوردية')),
                ('break_start', models.DateTimeField(blank=True, null=True, verbose_name='بداية الاستراحة')),
                ('break_end', models.DateTimeField(blank=True, null=True, verbose_name='نهاية الاستراحة')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='موقع العمل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='الوردية نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='hr_management.employeeattendance', verbose_name='سجل الحضور')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_shifts', to='hr_management.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'وردية عمل',
                'verbose_name_plural': 'ورديات العمل',
                'ordering': ['check_in'],
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Subtask Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Subtask Description')),
                ('status', models.CharField(choices=[('to_do', 'To Do'), ('doing', 'Doing'), ('done', 'Done')], default='to_do', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('estimated_minutes', models.IntegerField(default=15, verbose_name='Estimated Time (minutes)')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True, verbose_name='Paused At')),
                ('total_pause_time', models.IntegerField(default=0, verbose_name='Total Pause Time (minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Subtask Notes')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('parent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='hr_management.task')),
            ],
            options={
                'verbose_name': 'Subtask',
                'verbose_name_plural': 'Subtasks',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
