# Generated by Django 4.2.13 on 2025-10-05 07:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0022_alter_employeeattendance_date_workshift_subtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفريق')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الفريق')),
                ('is_active', models.BooleanField(default=True, verbose_name='فريق نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_teams', to=settings.AUTH_USER_MODEL, verbose_name='منشئ الفريق')),
                ('team_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to='hr_management.employee', verbose_name='قائد الفريق')),
            ],
            options={
                'verbose_name': 'فريق',
                'verbose_name_plural': 'فرق',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='admin_comment',
            field=models.TextField(blank=True, null=True, verbose_name='تعليق الأدمن'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_paid',
            field=models.BooleanField(blank=True, null=True, verbose_name='إجازة مدفوعة الأجر'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تمت المراجعة بواسطة'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 5, 7, 20, 51, 253342, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
        migrations.CreateModel(
            name='TeamTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_reassign', models.BooleanField(default=True, verbose_name='يمكن إعادة التكليف')),
                ('team_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10, verbose_name='أولوية الفريق')),
                ('team_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الفريق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_task_assignments', to=settings.AUTH_USER_MODEL, verbose_name='تم التكليف بواسطة')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_assignment', to='hr_management.task', verbose_name='المهمة')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='hr_management.team', verbose_name='الفريق')),
            ],
            options={
                'verbose_name': 'مهمة فريق',
                'verbose_name_plural': 'مهام الفرق',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='hr_management.team', verbose_name='Assigned Team'),
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', 'عضو'), ('senior_member', 'عضو أقدم'), ('assistant_leader', 'مساعد قائد')], default='member', max_length=20, verbose_name='الدور')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('is_active', models.BooleanField(default=True, verbose_name='عضوية نشطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='hr_management.employee', verbose_name='الموظف')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='hr_management.team', verbose_name='الفريق')),
            ],
            options={
                'verbose_name': 'عضوية فريق',
                'verbose_name_plural': 'عضويات الفرق',
                'ordering': ['team__name', 'role', 'employee__name'],
                'unique_together': {('team', 'employee')},
            },
        ),
    ]
