# Generated by Django 4.2.13 on 2025-10-05 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0023_team_leaverequest_admin_comment_leaverequest_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت الدخول'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت الخروج'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='is_paid_leave',
            field=models.BooleanField(default=True, verbose_name='إجازة مدفوعة'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='status',
            field=models.CharField(choices=[('present', 'حاضر'), ('late', 'متأخر'), ('absent', 'غائب'), ('on_leave', 'في إجازة')], default='present', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='total_break_time',
            field=models.IntegerField(default=0, verbose_name='إجمالي وقت الاستراحة (دقائق)'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 5, 7, 26, 24, 965349, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
