# Generated by Django 4.2.13 on 2025-10-05 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0024_workshift_check_in_time_workshift_check_out_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 5, 8, 24, 6, 699101, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
