# Generated by Django 4.2.13 on 2025-10-06 04:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0025_alter_employeeattendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='checkin_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='خط عرض الدخول'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='checkin_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='خط طول الدخول'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='checkout_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='خط عرض الخروج'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='checkout_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='خط طول الخروج'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 6, 4, 16, 32, 886708, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Main Office', max_length=200, verbose_name='اسم المكتب')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='خط الطول')),
                ('radius_meters', models.PositiveIntegerField(default=100, verbose_name='نطاق المسموح (متر)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('set_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='تم تعيينه بواسطة')),
            ],
            options={
                'verbose_name': 'موقع المكتب',
                'verbose_name_plural': 'مواقع المكاتب',
                'ordering': ['-created_at'],
            },
        ),
    ]
