# Generated by Django 4.2.13 on 2025-10-06 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0026_workshift_checkin_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 6, 4, 27, 13, 11743, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
