# Generated by Django 4.2.13 on 2025-10-06 05:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0027_alter_employeeattendance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWalletSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_system', to='hr_management.employee', verbose_name='الموظف')),
            ],
        ),
        migrations.CreateModel(
            name='MultiWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_type', models.CharField(choices=[('main', 'Main Wallet'), ('reimbursement', 'Reimbursement Wallet'), ('advance', 'Advance Wallet')], max_length=20, verbose_name='نوع المحفظة')),
                ('transaction_type', models.CharField(choices=[('salary_credit', 'Salary Credit'), ('bonus_credit', 'Bonus Credit'), ('advance_withdrawal', 'Advance Withdrawal'), ('manual_withdrawal', 'Manual Withdrawal'), ('manual_deposit', 'Manual Deposit'), ('advance_deduction', 'Advance Deduction'), ('reimbursement_payment', 'Reimbursement Payment'), ('reimbursement_approved', 'Reimbursement Approved'), ('reimbursement_paid', 'Reimbursement Paid'), ('advance_taken', 'Advance Taken'), ('advance_repaid', 'Advance Repaid')], max_length=30, verbose_name='نوع المعاملة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'Legacy Wallet (Deprecated)'},
        ),
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Legacy Wallet Transaction (Deprecated)'},
        ),
        migrations.AddField(
            model_name='reimbursementrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة'),
        ),
        migrations.AddField(
            model_name='reimbursementrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reimbursements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reimbursementrequest',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع'),
        ),
        migrations.AddField(
            model_name='reimbursementrequest',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_reimbursements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 6, 5, 6, 42, 519090, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'تحت المراجعة'), ('approved', 'موافقة'), ('paid', 'تم الدفع'), ('rejected', 'رفض')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_wallet', to='hr_management.employee', verbose_name='الموظف'),
        ),
        migrations.CreateModel(
            name='WalletTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('reimbursement_to_main', 'Reimbursement Payment'), ('main_to_advance', 'Advance Deduction')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('from_wallet_type', models.CharField(choices=[('main', 'Main Wallet'), ('reimbursement', 'Reimbursement Wallet'), ('advance', 'Advance Wallet')], max_length=20)),
                ('to_wallet_type', models.CharField(choices=[('main', 'Main Wallet'), ('reimbursement', 'Reimbursement Wallet'), ('advance', 'Advance Wallet')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from', to='hr_management.multiwallettransaction')),
                ('to_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to', to='hr_management.multiwallettransaction')),
                ('wallet_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='hr_management.employeewalletsystem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReimbursementWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='رصيد المبالغ المستردة')),
                ('wallet_system', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursement_wallet', to='hr_management.employeewalletsystem')),
            ],
        ),
        migrations.AddField(
            model_name='multiwallettransaction',
            name='reimbursement_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_management.reimbursementrequest'),
        ),
        migrations.AddField(
            model_name='multiwallettransaction',
            name='related_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_management.multiwallettransaction', verbose_name='المعاملة المرتبطة'),
        ),
        migrations.AddField(
            model_name='multiwallettransaction',
            name='wallet_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_transactions', to='hr_management.employeewalletsystem'),
        ),
        migrations.CreateModel(
            name='MainWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الرصيد الأساسي')),
                ('wallet_system', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_wallet', to='hr_management.employeewalletsystem')),
            ],
        ),
        migrations.CreateModel(
            name='AdvanceWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='رصيد السلف')),
                ('wallet_system', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advance_wallet', to='hr_management.employeewalletsystem')),
            ],
        ),
    ]
