# Generated by Django 4.2.13 on 2025-10-08 07:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0028_employeewalletsystem_multiwallettransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientComplaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('client_email', models.EmailField(max_length=254, verbose_name='بريد العميل الإلكتروني')),
                ('project_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المشروع')),
                ('project_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='رمز المشروع')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('urgent', 'عاجل')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان الشكوى')),
                ('description', models.TextField(verbose_name='تفاصيل الشكوى')),
                ('status', models.CharField(choices=[('pending_review', 'في انتظار المراجعة'), ('approved', 'معتمدة'), ('rejected', 'مرفوضة'), ('in_progress', 'قيد المعالجة'), ('resolved', 'محلولة'), ('closed', 'مغلقة')], default='pending_review', max_length=20, verbose_name='حالة الشكوى')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('review_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات المراجعة')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='سبب الرفض')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الحل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'شكوى عميل',
                'verbose_name_plural': 'شكاوى العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 8, 7, 28, 2, 843090, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
        migrations.CreateModel(
            name='ComplaintCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الفئة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الفئة')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='لون الفئة')),
                ('is_active', models.BooleanField(default=True, verbose_name='فئة نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_teams', models.ManyToManyField(blank=True, related_name='client_complaint_categories', to='hr_management.team', verbose_name='الفرق المخصصة')),
            ],
            options={
                'verbose_name': 'فئة الشكوى',
                'verbose_name_plural': 'فئات الشكاوى',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientComplaintTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='hr_management.clientcomplaint', verbose_name='الشكوى')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_complaint_task', to='hr_management.task', verbose_name='المهمة')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_management.team', verbose_name='الفريق')),
            ],
            options={
                'verbose_name': 'مهمة شكوى عميل',
                'verbose_name_plural': 'مهام شكاوى العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientComplaintStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('pending_review', 'في انتظار المراجعة'), ('approved', 'معتمدة'), ('rejected', 'مرفوضة'), ('in_progress', 'قيد المعالجة'), ('resolved', 'محلولة'), ('closed', 'مغلقة')], max_length=20, verbose_name='الحالة السابقة')),
                ('new_status', models.CharField(choices=[('pending_review', 'في انتظار المراجعة'), ('approved', 'معتمدة'), ('rejected', 'مرفوضة'), ('in_progress', 'قيد المعالجة'), ('resolved', 'محلولة'), ('closed', 'مغلقة')], max_length=20, verbose_name='الحالة الجديدة')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='سبب التغيير')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التغيير')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='غيرها')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='hr_management.clientcomplaint', verbose_name='الشكوى')),
            ],
            options={
                'verbose_name': 'تاريخ حالة شكوى عميل',
                'verbose_name_plural': 'تاريخ حالات شكاوى العملاء',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientComplaintComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='التعليق')),
                ('is_internal', models.BooleanField(default=True, verbose_name='تعليق داخلي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hr_management.clientcomplaint', verbose_name='الشكوى')),
            ],
            options={
                'verbose_name': 'تعليق شكوى عميل',
                'verbose_name_plural': 'تعليقات شكاوى العملاء',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientComplaintAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(verbose_name='رابط الملف')),
                ('file_name', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('uploaded_by', models.CharField(choices=[('client', 'العميل'), ('admin', 'الإدارة')], default='client', max_length=20, verbose_name='رفعه')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='hr_management.clientcomplaint', verbose_name='الشكوى')),
            ],
            options={
                'verbose_name': 'مرفق شكوى عميل',
                'verbose_name_plural': 'مرفقات شكاوى العملاء',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='clientcomplaint',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_management.complaintcategory', verbose_name='فئة الشكوى'),
        ),
        migrations.AddField(
            model_name='clientcomplaint',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_complaints', to=settings.AUTH_USER_MODEL, verbose_name='حلها'),
        ),
        migrations.AddField(
            model_name='clientcomplaint',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_complaints', to=settings.AUTH_USER_MODEL, verbose_name='راجعها'),
        ),
        migrations.AddField(
            model_name='employee',
            name='complaint_categories',
            field=models.ManyToManyField(blank=True, related_name='handling_employees', to='hr_management.complaintcategory', verbose_name='فئات الشكاوى التي يمكن التعامل معها'),
        ),
        migrations.CreateModel(
            name='ClientComplaintAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التخصيص')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات التخصيص')),
                ('is_active', models.BooleanField(default=True, verbose_name='تخصيص نشط')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='خصص بواسطة')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hr_management.clientcomplaint', verbose_name='الشكوى')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_complaint_assignments', to='hr_management.team', verbose_name='الفريق')),
            ],
            options={
                'verbose_name': 'تخصيص شكوى عميل',
                'verbose_name_plural': 'تخصيصات شكاوى العملاء',
                'ordering': ['-assigned_at'],
                'unique_together': {('complaint', 'team')},
            },
        ),
    ]
