# Generated by Django 4.2.13 on 2025-10-08 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0029_clientcomplaint_alter_employeeattendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='complaint_categories',
            field=models.ManyToManyField(blank=True, related_name='handling_teams', to='hr_management.complaintcategory', verbose_name='فئات الشكاوى التي يمكن للفريق التعامل معها'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 8, 8, 1, 17, 570299, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
