# Generated by Django 4.2.13 on 2025-10-11 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0031_alter_clientcomplaintstatushistory_changed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 11, 9, 45, 47, 93195, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
