# Generated by Django 4.2.13 on 2025-10-11 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0033_alter_employeeattendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcomplaintaccesstoken',
            name='is_permanent',
            field=models.BooleanField(default=True, verbose_name='رابط دائم'),
        ),
        migrations.AlterField(
            model_name='clientcomplaintaccesstoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 11, 13, 45, 2, 986094, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
