# Generated by Django 4.2.13 on 2025-10-14 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0035_clientcomplaintaccesstoken_is_permanent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcomplaintcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'تعليق شكوى عميل', 'verbose_name_plural': 'تعليقات شكاوى العملاء'},
        ),
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='clientcomplaint',
            name='client_phone',
            field=models.CharField(default=201201760623, max_length=20, verbose_name='رقم هاتف العميل'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 14, 4, 29, 49, 772814, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
