# Generated by Django 4.2.13 on 2025-10-14 04:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0036_add_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcomplaint',
            name='client_phone',
            field=models.CharField(help_text='رقم الهاتف مطلوب للتواصل', max_length=20, verbose_name='رقم هاتف العميل'),
        ),
        migrations.AlterField(
            model_name='clientcomplaint',
            name='status',
            field=models.CharField(default='pending_review', max_length=50, verbose_name='حالة الشكوى'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 14, 4, 48, 0, 853965, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
        migrations.CreateModel(
            name='ClientComplaintStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Status Name')),
                ('label', models.CharField(max_length=100, verbose_name='Display Label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Badge Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('status_type', models.CharField(choices=[('default', 'Default Status'), ('custom', 'Custom Status')], default='custom', max_length=10, verbose_name='Status Type')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('can_be_set_by_admin', models.BooleanField(default=True, verbose_name='Can be set by admin')),
                ('is_final_status', models.BooleanField(default=False, verbose_name='Is final status (cannot be changed)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_complaint_statuses', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Client Complaint Status',
                'verbose_name_plural': 'Client Complaint Statuses',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='clientcomplaint',
            name='custom_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='hr_management.clientcomplaintstatus', verbose_name='Custom Status'),
        ),
    ]
