# Generated by Django 4.2.13 on 2025-10-14 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0038_alter_employeeattendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 14, 5, 20, 39, 271229, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
