# Generated by Django 4.2.13 on 2025-10-14 08:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0039_alter_employeeattendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_subtasks', to='hr_management.employee', verbose_name='Assigned Employee'),
        ),
        migrations.AlterField(
            model_name='clientcomplaintstatushistory',
            name='new_status',
            field=models.CharField(choices=[('pending_review', 'في انتظار المراجعة'), ('approved', 'معتمدة'), ('rejected', 'مرفوضة'), ('in_progress', 'قيد المعالجة'), ('resolved', 'محلولة'), ('closed', 'مغلقة'), ('custom', 'حالة مخصصة')], max_length=20, verbose_name='الحالة الجديدة'),
        ),
        migrations.AlterField(
            model_name='clientcomplaintstatushistory',
            name='old_status',
            field=models.CharField(choices=[('pending_review', 'في انتظار المراجعة'), ('approved', 'معتمدة'), ('rejected', 'مرفوضة'), ('in_progress', 'قيد المعالجة'), ('resolved', 'محلولة'), ('closed', 'مغلقة'), ('custom', 'حالة مخصصة')], max_length=20, verbose_name='الحالة السابقة'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 14, 8, 29, 31, 438491, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
