# Generated by Django 4.2.13 on 2025-10-14 09:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0040_subtask_assigned_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 14, 9, 2, 57, 46422, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='hr_management.employee'),
        ),
    ]
