# Generated by Django 4.2.13 on 2025-10-15 10:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0041_alter_employeeattendance_date_alter_task_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 15, 10, 46, 57, 392848, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
        migrations.CreateModel(
            name='ClientComplaintEmployeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التخصيص')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات التخصيص')),
                ('is_active', models.BooleanField(default=True, verbose_name='تخصيص نشط')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='خصص بواسطة')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='hr_management.clientcomplaint', verbose_name='الشكوى')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_complaint_assignments', to='hr_management.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'تخصيص شكوى عميل للموظف',
                'verbose_name_plural': 'تخصيصات شكاوى العملاء للموظفين',
                'ordering': ['-assigned_at'],
                'unique_together': {('complaint', 'employee')},
            },
        ),
    ]
