# Generated by Django 4.2.13 on 2025-10-15 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0042_add_employee_complaint_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 15, 10, 57, 37, 416362, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
