# Generated by Django 4.2.13 on 2025-10-15 12:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0044_alter_employeeattendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 15, 12, 26, 36, 941233, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
        migrations.CreateModel(
            name='TeamComplaintAdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المنح')),
                ('is_active', models.BooleanField(default=True, verbose_name='صلاحية نشطة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('can_review', models.BooleanField(default=True, verbose_name='يمكن مراجعة الشكاوى')),
                ('can_assign', models.BooleanField(default=True, verbose_name='يمكن تخصيص الشكاوى')),
                ('can_update_status', models.BooleanField(default=True, verbose_name='يمكن تحديث حالة الشكاوى')),
                ('can_add_comments', models.BooleanField(default=True, verbose_name='يمكن إضافة تعليقات')),
                ('can_create_tasks', models.BooleanField(default=True, verbose_name='يمكن إنشاء مهام')),
                ('can_manage_assignments', models.BooleanField(default=True, verbose_name='يمكن إدارة التخصيصات')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='منحت بواسطة')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_admin_permission', to='hr_management.team', verbose_name='الفريق')),
            ],
            options={
                'verbose_name': 'صلاحية إدارة شكاوى للفريق',
                'verbose_name_plural': 'صلاحيات إدارة الشكاوى للفرق',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeComplaintAdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المنح')),
                ('is_active', models.BooleanField(default=True, verbose_name='صلاحية نشطة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('can_review', models.BooleanField(default=True, verbose_name='يمكن مراجعة الشكاوى')),
                ('can_assign', models.BooleanField(default=True, verbose_name='يمكن تخصيص الشكاوى')),
                ('can_update_status', models.BooleanField(default=True, verbose_name='يمكن تحديث حالة الشكاوى')),
                ('can_add_comments', models.BooleanField(default=True, verbose_name='يمكن إضافة تعليقات')),
                ('can_create_tasks', models.BooleanField(default=True, verbose_name='يمكن إنشاء مهام')),
                ('can_manage_assignments', models.BooleanField(default=True, verbose_name='يمكن إدارة التخصيصات')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_admin_permission', to='hr_management.employee', verbose_name='الموظف')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='منحت بواسطة')),
            ],
            options={
                'verbose_name': 'صلاحية إدارة شكاوى للموظف',
                'verbose_name_plural': 'صلاحيات إدارة الشكاوى للموظفين',
                'ordering': ['-granted_at'],
            },
        ),
    ]
