# Generated by Django 4.2.13 on 2025-10-16 08:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0046_add_new_complaint_admin_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcomplaint',
            name='client_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_complaints', to=settings.AUTH_USER_MODEL, verbose_name='حساب العميل'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 16, 8, 50, 55, 392091, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('manager', 'Manager'), ('client', 'Client')], default='employee', max_length=20),
        ),
    ]
