# Generated by Django 4.2.13 on 2025-10-16 11:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0047_clientcomplaint_client_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcomplaint',
            name='automated_status',
            field=models.CharField(blank=True, help_text='Automated status based on response timing', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientcomplaint',
            name='delay_status',
            field=models.CharField(blank=True, help_text='Indicates if delayed by system or client', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientcomplaint',
            name='last_responder',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('system', 'System')], help_text='Who responded last: client or system', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientcomplaint',
            name='last_response_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last response (client or system)', null=True),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 16, 11, 33, 28, 992521, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
        migrations.CreateModel(
            name='TicketDelayThreshold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('threshold_type', models.CharField(choices=[('global', 'Global Default'), ('priority', 'Priority-Based'), ('custom', 'Per-Ticket Custom')], default='global', max_length=20)),
                ('priority', models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], help_text='Only for priority-based thresholds', max_length=20, null=True)),
                ('system_response_hours', models.IntegerField(default=24, help_text='Hours allowed for system/support to respond before marked as delayed')),
                ('client_response_hours', models.IntegerField(default=48, help_text='Hours allowed for client to respond before marked as delayed')),
                ('auto_close_hours', models.IntegerField(default=48, help_text='Hours after resolution before auto-closing if no client confirmation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ticket Delay Threshold',
                'verbose_name_plural': 'Ticket Delay Thresholds',
                'ordering': ['threshold_type', 'priority'],
                'unique_together': {('threshold_type', 'priority')},
            },
        ),
        migrations.AddField(
            model_name='clientcomplaint',
            name='custom_threshold',
            field=models.ForeignKey(blank=True, help_text='Custom thresholds for this specific ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_with_custom_threshold', to='hr_management.ticketdelaythreshold'),
        ),
    ]
