# Generated by Django 4.2.13 on 2025-10-17 12:01

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0049_alter_employeeattendance_date_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 17, 12, 1, 20, 198046, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
        migrations.CreateModel(
            name='WeeklyShiftSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'الأحد'), (1, 'الإثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس'), (5, 'الجمعة'), (6, 'السبت')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='يوم الأسبوع')),
                ('start_time', models.TimeField(verbose_name='وقت البداية')),
                ('end_time', models.TimeField(verbose_name='وقت النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_shifts', to='hr_management.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'جدول دوام أسبوعي',
                'verbose_name_plural': 'جداول الدوام الأسبوعية',
                'ordering': ['employee', 'day_of_week'],
                'indexes': [models.Index(fields=['employee', 'day_of_week'], name='hr_manageme_employe_bc14e5_idx'), models.Index(fields=['is_active'], name='hr_manageme_is_acti_78c1b0_idx')],
                'unique_together': {('employee', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='ShiftOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('override_type', models.CharField(choices=[('custom', 'ساعات مخصصة'), ('day_off', 'يوم عطلة'), ('vacation', 'إجازة'), ('sick_leave', 'إجازة مرضية'), ('holiday', 'عطلة رسمية')], max_length=20, verbose_name='نوع الاستثناء')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='وقت البداية')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='وقت النهاية')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_shift_overrides', to=settings.AUTH_USER_MODEL, verbose_name='وافق عليه')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_overrides', to='hr_management.employee', verbose_name='الموظف')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_override_requests', to=settings.AUTH_USER_MODEL, verbose_name='طلب بواسطة')),
            ],
            options={
                'verbose_name': 'استثناء دوام',
                'verbose_name_plural': 'استثناءات الدوام',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['employee', 'date'], name='hr_manageme_employe_61a85b_idx'), models.Index(fields=['date', 'status'], name='hr_manageme_date_6ac301_idx'), models.Index(fields=['status'], name='hr_manageme_status_e33917_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ShiftAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('expected_start', models.TimeField(blank=True, null=True, verbose_name='وقت البداية المتوقع')),
                ('expected_end', models.TimeField(blank=True, null=True, verbose_name='وقت النهاية المتوقع')),
                ('actual_start', models.TimeField(blank=True, null=True, verbose_name='وقت البداية الفعلي')),
                ('actual_end', models.TimeField(blank=True, null=True, verbose_name='وقت النهاية الفعلي')),
                ('status', models.CharField(choices=[('scheduled', 'مجدول'), ('present', 'حاضر'), ('late', 'متأخر'), ('absent', 'غائب'), ('early_departure', 'مغادرة مبكرة'), ('overtime', 'وقت إضافي'), ('day_off', 'يوم عطلة')], default='scheduled', max_length=20, verbose_name='الحالة')),
                ('late_minutes', models.IntegerField(default=0, verbose_name='دقائق التأخير')),
                ('early_departure_minutes', models.IntegerField(default=0, verbose_name='دقائق المغادرة المبكرة')),
                ('overtime_minutes', models.IntegerField(default=0, verbose_name='دقائق الوقت الإضافي')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='مجموع الساعات')),
                ('auto_marked_absent', models.BooleanField(default=False, verbose_name='تم وضع علامة غائب تلقائياً')),
                ('requires_manager_approval', models.BooleanField(default=False, verbose_name='يتطلب موافقة المدير')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendances', to=settings.AUTH_USER_MODEL, verbose_name='وافق عليه')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_attendances', to='hr_management.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'حضور دوام',
                'verbose_name_plural': 'سجل الحضور',
                'ordering': ['-date', 'employee'],
                'indexes': [models.Index(fields=['employee', 'date'], name='hr_manageme_employe_62d275_idx'), models.Index(fields=['date', 'status'], name='hr_manageme_date_2bf5e6_idx'), models.Index(fields=['status'], name='hr_manageme_status_ef83ca_idx'), models.Index(fields=['auto_marked_absent'], name='hr_manageme_auto_ma_0ff6f1_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
