# Generated by Django 4.2.13 on 2025-10-22 07:44

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0050_alter_employeeattendance_date_weeklyshiftschedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_key', models.CharField(max_length=50, unique=True, verbose_name='Module Key')),
                ('module_name', models.CharField(max_length=100, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon Class/Name')),
                ('is_core', models.BooleanField(default=False, help_text='Core modules are always enabled and cannot be disabled', verbose_name='Core Module')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Module Definition',
                'verbose_name_plural': 'Module Definitions',
                'ordering': ['sort_order', 'module_name'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Client Name')),
                ('subdomain', models.SlugField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Subdomain can only contain lowercase letters, numbers, and hyphens', regex='^[a-z0-9-]+$')], verbose_name='Subdomain')),
                ('custom_domain', models.CharField(blank=True, help_text='e.g., client.myapp.com', max_length=255, null=True, verbose_name='Custom Domain (Optional)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/', verbose_name='Client Logo')),
                ('primary_color', models.CharField(default='#3498db', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #3498db)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Primary Color')),
                ('secondary_color', models.CharField(default='#2ecc71', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #2ecc71)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Secondary Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 22, 7, 44, 18, 512189, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
        migrations.CreateModel(
            name='TenantAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(help_text='Key name/description', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='hr_management.tenant')),
            ],
            options={
                'verbose_name': 'Tenant API Key',
                'verbose_name_plural': 'Tenant API Keys',
            },
        ),
        migrations.CreateModel(
            name='TenantModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_key', models.CharField(help_text='e.g., employees, attendance, wallet, tasks', max_length=50, verbose_name='Module Key')),
                ('module_name', models.CharField(max_length=100, verbose_name='Module Display Name')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='hr_management.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Module',
                'verbose_name_plural': 'Tenant Modules',
                'ordering': ['module_key'],
                'unique_together': {('tenant', 'module_key')},
            },
        ),
    ]
