# Generated by Django 4.2.13 on 2025-10-22 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0051_moduledefinition_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 22, 7, 45, 5, 588004, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
