# Generated by Django 4.2.13 on 2025-10-22 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0052_alter_employeeattendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 22, 8, 24, 19, 783179, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
