# Generated by Django 4.2.13 on 2025-10-31 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0053_alter_employeeattendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='related_tenants',
            field=models.ManyToManyField(blank=True, help_text='Other tenants that this tenant is associated with', related_name='referencing_tenants', to='hr_management.tenant', verbose_name='Related Tenants'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 31, 11, 37, 21, 912299, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
