# Generated by Django 5.1.4 on 2025-10-29 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0053_alter_employeeattendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 29, 12, 52, 38, 263057, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
