# Generated by Django 5.1.4 on 2025-10-29 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0054_alter_employeeattendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 29, 15, 13, 26, 951980, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
