# Generated by Django 4.2.13 on 2025-10-31 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0054_add_related_tenants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 31, 11, 37, 45, 14340, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
