# Generated by Django 4.2.13 on 2025-10-31 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0055_add_related_tenants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='related_tenants',
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 31, 13, 57, 58, 59676, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
