# Generated by Django 5.1.4 on 2025-10-31 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0056_alter_employeeattendance_date'),
        ('hr_management', '0056_remove_related_tenants'),
    ]

    operations = [
    ]
