# Generated by Django 5.1.4 on 2025-11-01 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0059_alter_employeeattendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 11, 1, 9, 8, 30, 469454, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
