# Generated by Django 5.1.4 on 2025-11-01 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0061_emailverificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 11, 1, 9, 15, 14, 946640, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
