# Generated by Django 5.1.4 on 2025-11-01 14:19

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0063_alter_employeeattendance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('password', models.CharField(max_length=128, verbose_name='كلمة المرور')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='آخر تسجيل دخول')),
            ],
            options={
                'verbose_name': 'عميل عام',
                'verbose_name_plural': 'عملاء عامون',
                'db_table': 'hr_management_globalclient',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 11, 1, 14, 19, 48, 752774, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
