# Generated by Django 5.1.4 on 2025-11-01 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0064_globalclient_alter_employeeattendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 11, 1, 14, 21, 19, 94762, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
