# Generated by Django 5.1.4 on 2025-11-02 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0067_alter_employeeattendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 11, 2, 8, 54, 25, 386301, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='total_pause_time',
            field=models.FloatField(default=0.0, verbose_name='Total Pause Time (minutes)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='total_pause_time',
            field=models.FloatField(default=0.0, verbose_name='Total Pause Time (minutes)'),
        ),
    ]
