# Generated by Django 5.1.4 on 2025-11-02 12:25

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0068_alter_employeeattendance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 11, 2, 12, 25, 33, 196003, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
        migrations.CreateModel(
            name='ShareableTaskLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Share Token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('view_count', models.IntegerField(default=0, verbose_name='View Count')),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Viewed')),
                ('allow_comments', models.BooleanField(default=False, verbose_name='Allow Comments')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_share_links', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_links', to='hr_management.task')),
            ],
            options={
                'verbose_name': 'Shareable Task Link',
                'verbose_name_plural': 'Shareable Task Links',
                'ordering': ['-created_at'],
            },
        ),
    ]
