# Generated by Django 5.1.4 on 2025-11-03 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0069_alter_employeeattendance_date_shareabletasklink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 11, 3, 11, 35, 35, 873742, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
