# Generated by Django 5.1.4 on 2025-11-05 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0070_alter_employeeattendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 11, 5, 11, 37, 9, 317620, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
