# Generated by Django 5.1.4 on 2025-11-11 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0071_alter_employeeattendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 11, 11, 14, 44, 11, 111643, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
