# Generated by Django 5.1.4 on 2025-11-11 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0072_alter_employeeattendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 11, 11, 15, 17, 28, 916786, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
