# Generated by Django 4.2.13 on 2025-11-14 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0072_remove_locationtrackingsummary_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='domain_type',
            field=models.CharField(choices=[('subdomain', 'Subdomain'), ('custom', 'Custom Domain')], default='subdomain', max_length=20, verbose_name='Domain Type'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 11, 14, 9, 17, 47, 639549, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='custom_domain',
            field=models.CharField(blank=True, help_text='e.g., mycompany.com (only if domain_type is custom)', max_length=255, null=True, unique=True, verbose_name='Custom Domain'),
        ),
    ]
