# Generated by Django 4.2.13 on 2025-11-14 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0073_tenant_domain_type_alter_employeeattendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='ssl_enabled',
            field=models.BooleanField(default=False, help_text='Whether SSL certificate is installed for this domain', verbose_name='SSL Enabled'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ssl_issued_at',
            field=models.DateTimeField(blank=True, help_text='When the SSL certificate was issued', null=True, verbose_name='SSL Issued At'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 11, 14, 9, 41, 16, 496000, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
