# Generated by Django 4.2.13 on 2025-11-14 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0074_add_ssl_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 11, 14, 9, 41, 23, 131799, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
    ]
