# Generated by Django 5.1.4 on 2025-11-12 17:56

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0075_alter_employeeattendance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم الفرع')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('latitude', models.DecimalField(decimal_places=8, help_text='خط العرض GPS للفرع', max_digits=10, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(decimal_places=8, help_text='خط الطول GPS للفرع', max_digits=11, verbose_name='خط الطول')),
                ('attendance_radius', models.IntegerField(default=100, help_text='المسافة المسموح بها للتسجيل من موقع الفرع (بالمتر)', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(5000)], verbose_name='نطاق التسجيل (متر)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('require_location', models.BooleanField(default=True, help_text='هل يجب على الموظفين أن يكونوا في نطاق الفرع للتسجيل؟', verbose_name='يتطلب التحقق من الموقع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='workshift',
            name='checkin_distance',
            field=models.FloatField(blank=True, help_text='المسافة من موقع الفرع عند تسجيل الدخول', null=True, verbose_name='مسافة تسجيل الدخول (متر)'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='checkin_within_radius',
            field=models.BooleanField(blank=True, null=True, verbose_name='داخل نطاق الدخول'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='checkout_distance',
            field=models.FloatField(blank=True, help_text='المسافة من موقع الفرع عند تسجيل الخروج', null=True, verbose_name='مسافة تسجيل الخروج (متر)'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='checkout_within_radius',
            field=models.BooleanField(blank=True, null=True, verbose_name='داخل نطاق الخروج'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 11, 12, 17, 56, 30, 400523, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='حقل قديم - استخدم علاقة branches بدلاً منه', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_employees', to='hr_management.branch', verbose_name='الفرع (قديم)'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='branches',
            field=models.ManyToManyField(blank=True, help_text='الفروع التي ستتأثر بهذه الإجازة', related_name='leave_requests', to='hr_management.branch', verbose_name='الفروع المتأثرة'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='الفرع الذي تم فيه تسجيل الحضور', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_shifts', to='hr_management.branch', verbose_name='الفرع'),
        ),
        migrations.CreateModel(
            name='EmployeeBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='هل هذا التعيين نشط حالياً؟', verbose_name='نشط')),
                ('assigned_date', models.DateField(default=datetime.date.today, help_text='تاريخ تعيين الموظف في هذا الفرع', verbose_name='تاريخ التعيين')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_employees', to='hr_management.branch', verbose_name='الفرع')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_branches', to='hr_management.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'تعيين موظف في فرع',
                'verbose_name_plural': 'تعيينات الموظفين في الفروع',
                'ordering': ['employee', 'branch'],
                'unique_together': {('employee', 'branch')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='branches',
            field=models.ManyToManyField(blank=True, help_text='الفروع التي يعمل فيها الموظف', related_name='assigned_employees', through='hr_management.EmployeeBranch', to='hr_management.branch', verbose_name='الفروع'),
        ),
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'الأحد'), (1, 'الاثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس'), (5, 'الجمعة'), (6, 'السبت')], help_text='0=الأحد, 1=الاثنين, ..., 6=السبت', verbose_name='يوم الأسبوع')),
                ('is_working_day', models.BooleanField(default=True, help_text='هل هذا يوم عمل أم يوم إجازة؟', verbose_name='يوم عمل')),
                ('shift_start_time', models.TimeField(blank=True, help_text='وقت بداية الدوام في هذا اليوم', null=True, verbose_name='وقت بداية الدوام')),
                ('shift_end_time', models.TimeField(blank=True, help_text='وقت نهاية الدوام في هذا اليوم', null=True, verbose_name='وقت نهاية الدوام')),
                ('is_remote_work', models.BooleanField(default=False, help_text='هل يمكن للموظف العمل عن بعد في هذا اليوم؟ (True = يمكن العمل عن بعد، False = يجب الحضور للفرع)', verbose_name='عمل عن بعد')),
                ('notes', models.TextField(blank=True, help_text='ملاحظات خاصة بهذا اليوم (اختياري)', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('employee_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedules', to='hr_management.employeebranch', verbose_name='تعيين الموظف في الفرع')),
            ],
            options={
                'verbose_name': 'جدول يومي',
                'verbose_name_plural': 'الجداول اليومية',
                'ordering': ['employee_branch', 'day_of_week'],
                'indexes': [models.Index(fields=['employee_branch', 'day_of_week'], name='hr_manageme_employe_be7b4a_idx'), models.Index(fields=['is_working_day'], name='hr_manageme_is_work_227074_idx')],
                'unique_together': {('employee_branch', 'day_of_week')},
            },
        ),
    ]
