# Generated by Django 5.1.4 on 2025-11-14 11:59

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0076_branch_workshift_checkin_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='domain_type',
            field=models.CharField(choices=[('subdomain', 'Subdomain'), ('custom', 'Custom Domain')], default='subdomain', max_length=20, verbose_name='Domain Type'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ssl_enabled',
            field=models.BooleanField(default=False, help_text='Whether SSL certificate is installed for this domain', verbose_name='SSL Enabled'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ssl_issued_at',
            field=models.DateTimeField(blank=True, help_text='When the SSL certificate was issued', null=True, verbose_name='SSL Issued At'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 11, 14, 11, 59, 0, 390715, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='custom_domain',
            field=models.CharField(blank=True, help_text='e.g., mycompany.com (only if domain_type is custom)', max_length=255, null=True, unique=True, verbose_name='Custom Domain'),
        ),
        migrations.CreateModel(
            name='LocationTrackingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('exit', 'خروج من منطقة العمل'), ('enter', 'دخول لمنطقة العمل'), ('ping', 'تحديث موقع')], max_length=10, verbose_name='نوع الحدث')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت الحدث')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='خط الطول')),
                ('distance_from_branch', models.IntegerField(help_text='المسافة المحسوبة من مركز الفرع', verbose_name='المسافة من الفرع (متر)')),
                ('within_radius', models.BooleanField(default=False, help_text='هل الموظف داخل نطاق الحضور المسموح', verbose_name='داخل النطاق')),
                ('duration_outside', models.IntegerField(blank=True, help_text='إجمالي الوقت خارج منطقة العمل (يُحسب عند العودة)', null=True, verbose_name='مدة الخروج (ثواني)')),
                ('battery_level', models.IntegerField(blank=True, null=True, verbose_name='مستوى البطارية (%)')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='دقة الموقع (متر)')),
                ('branch', models.ForeignKey(blank=True, help_text='الفرع الذي تم التحقق من المسافة منه', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_management.branch', verbose_name='الفرع')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_events', to='hr_management.employee', verbose_name='الموظف')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_events', to='hr_management.workshift', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'حدث تتبع موقع',
                'verbose_name_plural': 'أحداث تتبع المواقع',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['employee', 'timestamp'], name='hr_manageme_employe_62e190_idx'), models.Index(fields=['shift', 'event_type'], name='hr_manageme_shift_i_f2eb9f_idx'), models.Index(fields=['timestamp'], name='hr_manageme_timesta_7ba3b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationTrackingSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('total_exits', models.IntegerField(default=0, verbose_name='عدد مرات الخروج')),
                ('total_time_outside', models.IntegerField(default=0, verbose_name='إجمالي الوقت خارج المنطقة (ثواني)')),
                ('longest_exit_duration', models.IntegerField(default=0, verbose_name='أطول مدة خروج (ثواني)')),
                ('first_ping', models.DateTimeField(blank=True, null=True, verbose_name='أول تحديث')),
                ('last_ping', models.DateTimeField(blank=True, null=True, verbose_name='آخر تحديث')),
                ('currently_outside', models.BooleanField(default=False, verbose_name='خارج المنطقة حالياً')),
                ('current_exit_started', models.DateTimeField(blank=True, null=True, verbose_name='وقت بدء الخروج الحالي')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_summaries', to='hr_management.employee', verbose_name='الموظف')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_summary', to='hr_management.workshift', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'ملخص تتبع الموقع اليومي',
                'verbose_name_plural': 'ملخصات تتبع المواقع اليومية',
                'ordering': ['-date', 'employee__name'],
                'indexes': [models.Index(fields=['employee', 'date'], name='hr_manageme_employe_bc33ad_idx'), models.Index(fields=['date', 'currently_outside'], name='hr_manageme_date_5f213e_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
