# Generated by Django 4.2.13 on 2025-11-18 14:41

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0077_tenant_domain_type_tenant_ssl_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 11, 18, 14, 41, 21, 458796, tzinfo=datetime.timezone.utc), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='subdomain',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Subdomain can only contain lowercase letters, numbers, and hyphens', regex='^[a-z0-9-]+$')], verbose_name='Subdomain'),
        ),
    ]
