# Generated by Django 4.2.13 on 2025-11-09 12:55

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True, verbose_name='الشخص المسؤول')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='الهاتف')),
                ('phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='هاتف إضافي')),
                ('category', models.CharField(blank=True, choices=[('small', 'صغير'), ('medium', 'متوسط'), ('large', 'كبير')], max_length=20, null=True, verbose_name='الفئة')),
                ('status', models.CharField(choices=[('potential', 'عميل محتمل'), ('active', 'عميل نشط'), ('inactive', 'غير نشط'), ('suspended', 'معلق')], default='potential', max_length=20, verbose_name='الحالة')),
                ('custom_data', models.JSONField(blank=True, default=dict, verbose_name='البيانات المخصصة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to=settings.AUTH_USER_MODEL, verbose_name='مسند إلى')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الوحدة')),
                ('short_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='اسم مختصر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('custom_fields', models.JSONField(blank=True, default=list, verbose_name='الحقول المخصصة')),
                ('is_countable', models.BooleanField(default=True, verbose_name='قابل للعد')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product_units', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
            ],
            options={
                'verbose_name': 'وحدة المنتج',
                'verbose_name_plural': 'وحدات المنتجات',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SimpleProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم المنتج/الخدمة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('product_type', models.CharField(choices=[('product', 'منتج'), ('service', 'خدمة')], default='product', max_length=20, verbose_name='النوع')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر الأساسي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_simple_products', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
            ],
            options={
                'verbose_name': 'منتج/خدمة',
                'verbose_name_plural': 'المنتجات والخدمات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='اسم التصنيف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='أيقونة')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='اللون')),
                ('custom_fields', models.JSONField(blank=True, default=list, verbose_name='الحقول المخصصة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='صورة التصنيف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product_categories', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
            ],
            options={
                'verbose_name': 'تصنيف المنتج',
                'verbose_name_plural': 'تصنيفات المنتجات',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر لكل وحدة')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='المبلغ الإجمالي')),
                ('visit_interval_days', models.IntegerField(default=14, help_text='عدد الأيام بين كل زيارة', verbose_name='فترة الزيارة (بالأيام)')),
                ('last_visit_date', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر زيارة')),
                ('next_visit_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الزيارة الدورية')),
                ('reminder_days_before', models.IntegerField(default=1, help_text='عدد الأيام قبل الموعد للتذكير', verbose_name='التذكير قبل الموعد بـ (أيام)')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('waiting_visit', 'في انتظار الزيارة'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='new', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('distributed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التوزيع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='pos_management.client', verbose_name='العميل')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_distributions', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='pos_management.simpleproduct', verbose_name='المنتج/الخدمة')),
            ],
            options={
                'verbose_name': 'توزيع',
                'verbose_name_plural': 'التوزيعات',
                'ordering': ['-distributed_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم نوع العميل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='أيقونة')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='اللون')),
                ('custom_fields', models.JSONField(default=list, verbose_name='الحقول المخصصة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_types', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
            ],
            options={
                'verbose_name': 'نوع العميل',
                'verbose_name_plural': 'أنواع العملاء',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الكمية الحالية')),
                ('minimum_quantity', models.DecimalField(decimal_places=2, default=0, help_text='عند الوصول لهذه الكمية، يظهر تحذير', max_digits=10, verbose_name='الحد الأدنى للكمية')),
                ('maximum_quantity', models.DecimalField(decimal_places=2, default=100, help_text='السعة التخزينية القصوى', max_digits=10, verbose_name='الحد الأقصى للكمية')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الصلاحية')),
                ('location', models.CharField(blank=True, help_text='مثل: مخزن رئيسي، ثلاجة، رف 3', max_length=200, null=True, verbose_name='موقع التخزين')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='pos_management.client', verbose_name='العميل')),
                ('last_distribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_updates', to='pos_management.distribution', verbose_name='آخر توزيعة')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_updates', to=settings.AUTH_USER_MODEL, verbose_name='آخر تحديث بواسطة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_inventory', to='pos_management.simpleproduct', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'مخزون عميل',
                'verbose_name_plural': 'مخزون العملاء',
                'ordering': ['client', 'product'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='pos_management.clienttype', verbose_name='نوع العميل'),
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه'),
        ),
        migrations.CreateModel(
            name='CategoryUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_pieces_per_unit', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='عدد الحبات الافتراضي في الوحدة')),
                ('is_primary', models.BooleanField(default=False, verbose_name='الوحدة الأساسية')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_units', to='pos_management.productcategory', verbose_name='التصنيف')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_units', to='pos_management.productunit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'ربط تصنيف-وحدة',
                'verbose_name_plural': 'روابط التصنيفات-الوحدات',
                'ordering': ['category', 'display_order', 'unit'],
            },
        ),
        migrations.CreateModel(
            name='AdvancedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='اسم المنتج')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='كود المنتج (SKU)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('custom_data', models.JSONField(blank=True, default=dict, verbose_name='البيانات المخصصة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='صورة المنتج')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='السعر الأساسي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_featured', models.BooleanField(default=False, verbose_name='منتج مميز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='pos_management.productcategory', verbose_name='التصنيف')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_advanced_products', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
            ],
            options={
                'verbose_name': 'منتج متقدم',
                'verbose_name_plural': 'المنتجات المتقدمة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductUnitStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pieces_per_unit', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='عدد الحبات في الوحدة')),
                ('quantity_in_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='الكمية في المخزن')),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='الحد الأدنى للمخزون')),
                ('custom_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات الوحدة المخصصة')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='سعر الوحدة')),
                ('is_primary', models.BooleanField(default=False, verbose_name='الوحدة الأساسية')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_units', to='pos_management.advancedproduct', verbose_name='المنتج')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_units', to='pos_management.productunit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'مخزون وحدة المنتج',
                'verbose_name_plural': 'مخزون وحدات المنتجات',
                'ordering': ['product', 'display_order', 'unit'],
                'indexes': [models.Index(fields=['product', 'unit'], name='pos_managem_product_074164_idx'), models.Index(fields=['quantity_in_stock'], name='pos_managem_quantit_748ee5_idx'), models.Index(fields=['is_primary'], name='pos_managem_is_prim_49db4d_idx')],
                'unique_together': {('product', 'unit')},
            },
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['is_active', 'display_order'], name='pos_managem_is_acti_ef0366_idx'),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['name'], name='pos_managem_name_ebdcc2_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['is_active', 'display_order'], name='pos_managem_is_acti_3e62ce_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['name'], name='pos_managem_name_c5411a_idx'),
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['client', 'status'], name='pos_managem_client__857ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['next_visit_date'], name='pos_managem_next_vi_45dd8e_idx'),
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['status'], name='pos_managem_status_729bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='clientinventory',
            index=models.Index(fields=['client', 'product'], name='pos_managem_client__de1d80_idx'),
        ),
        migrations.AddIndex(
            model_name='clientinventory',
            index=models.Index(fields=['current_quantity'], name='pos_managem_current_abe652_idx'),
        ),
        migrations.AddIndex(
            model_name='clientinventory',
            index=models.Index(fields=['expiry_date'], name='pos_managem_expiry__5cb2b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientinventory',
            unique_together={('client', 'product')},
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status'], name='pos_managem_status_3c7148_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_type'], name='pos_managem_client__53985d_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['category'], name='pos_managem_categor_917ff9_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryunit',
            index=models.Index(fields=['category', 'unit'], name='pos_managem_categor_984c06_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryunit',
            index=models.Index(fields=['is_primary'], name='pos_managem_is_prim_8fc090_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryunit',
            unique_together={('category', 'unit')},
        ),
        migrations.AddIndex(
            model_name='advancedproduct',
            index=models.Index(fields=['category', 'is_active'], name='pos_managem_categor_752cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedproduct',
            index=models.Index(fields=['sku'], name='pos_managem_sku_26f65b_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedproduct',
            index=models.Index(fields=['name'], name='pos_managem_name_8b7329_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedproduct',
            index=models.Index(fields=['-created_at'], name='pos_managem_created_cc966d_idx'),
        ),
    ]
