# Generated by Django 4.2.13 on 2025-11-18 14:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryunit',
            options={'ordering': ['category', 'unit'], 'verbose_name': 'ربط تصنيف-وحدة', 'verbose_name_plural': 'روابط التصنيفات-الوحدات'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['name'], 'verbose_name': 'تصنيف المنتج', 'verbose_name_plural': 'تصنيفات المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='productunit',
            options={'ordering': ['name'], 'verbose_name': 'وحدة المنتج', 'verbose_name_plural': 'وحدات المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='productunitstock',
            options={'ordering': ['product', 'unit'], 'verbose_name': 'وحدة عرض المنتج', 'verbose_name_plural': 'وحدات عرض المنتجات'},
        ),
        migrations.RemoveIndex(
            model_name='advancedproduct',
            name='pos_managem_categor_752cd4_idx',
        ),
        migrations.RemoveIndex(
            model_name='advancedproduct',
            name='pos_managem_sku_26f65b_idx',
        ),
        migrations.RemoveIndex(
            model_name='productcategory',
            name='pos_managem_is_acti_3e62ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='productunit',
            name='pos_managem_is_acti_ef0366_idx',
        ),
        migrations.RemoveIndex(
            model_name='productunitstock',
            name='pos_managem_quantit_748ee5_idx',
        ),
        migrations.RemoveField(
            model_name='advancedproduct',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='advancedproduct',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='advancedproduct',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='categoryunit',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='productunitstock',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='productunitstock',
            name='minimum_stock',
        ),
        migrations.RemoveField(
            model_name='productunitstock',
            name='quantity_in_stock',
        ),
        migrations.AddField(
            model_name='advancedproduct',
            name='minimum_stock_pieces',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='الحد الأدنى للمخزون بالقطع'),
        ),
        migrations.AddField(
            model_name='advancedproduct',
            name='total_stock_pieces',
            field=models.DecimalField(decimal_places=2, default=0, help_text='المخزون الكلي بالقطع - الوحدات تحسب منه تلقائياً', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='المخزون الكلي بالقطع'),
        ),
        migrations.AlterField(
            model_name='productunitstock',
            name='pieces_per_unit',
            field=models.DecimalField(decimal_places=2, default=1, help_text='كم قطعة في هذه الوحدة؟ مثال: 24 قطعة في الكرتون', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='عدد القطع في الوحدة'),
        ),
        migrations.AddIndex(
            model_name='advancedproduct',
            index=models.Index(fields=['category'], name='pos_managem_categor_e0ccbf_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['is_active'], name='pos_managem_is_acti_964407_idx'),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['is_active'], name='pos_managem_is_acti_ebe7a6_idx'),
        ),
    ]
